# Generated by Django 4.1 on 2023-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='conversa',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
