# Generated by Django 4.1 on 2023-06-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reset_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
