# Generated by Django 4.1 on 2023-07-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
    ]
