# Generated by Django 4.1 on 2023-07-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='peso',
        ),
    ]
