# Generated by Django 4.1 on 2023-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_persona_altura_remove_persona_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='altura',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='peso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
