# Generated by Django 4.1 on 2023-07-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_remove_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-12-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-12-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='tn_peso',
            field=models.DateTimeField(auto_now_add=True, default='2000-12-30'),
            preserve_default=False,
        ),
    ]
